### Login to get JWT token
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "staff",
  "password": "password"
}

### Get all menu items using JWT token
# Replace the token with the one received from the login request
GET http://localhost:8080/api/menuitems
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJtZW51LWFwaS1hdWRpZW5jZSIsImlzcyI6Im1lbnUtYXBpIiwidXNlcklkIjoyLCJjdXN0b21lcklkIjoyLCJyb2xlIjoiU1RBRkYiLCJleHAiOjE3NTE3Mzk4NTd9.jrK67_JCsgi0P01CyIL3jVCTsPG7mMtDe1-10zFVKJo

### Get menu item by ID using JWT token
# Replace the token with the one received from the login request
GET http://localhost:8080/api/menuitems/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJtZW51LWFwaS1hdWRpZW5jZSIsImlzcyI6Im1lbnUtYXBpIiwidXNlcklkIjoyLCJjdXN0b21lcklkIjoyLCJyb2xlIjoiU1RBRkYiLCJleHAiOjE3NTE3Mzk4NTd9.jrK67_JCsgi0P01CyIL3jVCTsPG7mMtDe1-10zFVKJo

### Create new menu item using JWT token
# Replace the token with the one received from the login request
POST http://localhost:8080/api/menuitems
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJtZW51LWFwaS1hdWRpZW5jZSIsImlzcyI6Im1lbnUtYXBpIiwicHJpbmNpcGFsIjoiYWRtaW4iLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3NTAyMzk3ODR9.0XMhHiE5KLbXxscKlzZev-dt0VMoVOxQTAuw-zTu8ws
Content-Type: application/json

{
  "name": "Cappuccino",
  "description": "Espresso with steamed milk and foam",
  "price": 3.99
}

### Update menu item using JWT token
PUT http://localhost:8080/api/menuitems/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJtZW51LWFwaS1hdWRpZW5jZSIsImlzcyI6Im1lbnUtYXBpIiwicHJpbmNpcGFsIjoiYWRtaW4iLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3NTAyMzk3ODR9.0XMhHiE5KLbXxscKlzZev-dt0VMoVOxQTAuw-zTu8ws
Content-Type: application/json

{
  "name": "Cappuccino De Luxe",
  "description": "Espresso with steamed milk and foam",
  "price": 3.99
}


### Delete menu item using JWT token
DELETE http://localhost:8080/api/menuitems/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJtZW51LWFwaS1hdWRpZW5jZSIsImlzcyI6Im1lbnUtYXBpIiwicHJpbmNpcGFsIjoiYWRtaW4iLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3NTAyMzk3ODR9.0XMhHiE5KLbXxscKlzZev-dt0VMoVOxQTAuw-zTu8ws


### Get orders
GET http://localhost:8080/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJtZW51LWFwaS1hdWRpZW5jZSIsImlzcyI6Im1lbnUtYXBpIiwidXNlcklkIjoyLCJjdXN0b21lcklkIjoyLCJyb2xlIjoiU1RBRkYiLCJleHAiOjE3NTE3NjI1Mzl9.TvJYk1lH7Xt5L72KvYjUUzS2P5Nai-rRv8VwdoRHMHI
